import image500x200 from '../../../static/images/500x200.jpg';

import { PageInfo } from './BlockPageOverview';

export const CONTENT_PAGES_MOCK: PageInfo[] = [
	{
		content_width: 'REGULAR',
		created_at: '2020-01-24T13:46:05.862681+00:00',
		description:
			'Gedetacheerde leerkracht Katrijn draagt haar steentje bij: ze verrijkte het aanbod op Het Archief voor Onderwijs met collecties voor de kunstvakken. Geef jij les in een architecturale richting of wil je werken rond bouwen en wonen? Dan geef je jouw lessen met deze acht collecties boordevol actueel beeldmateriaal nog meer kleur.',
		title: 'Test buttons',
		id: 52,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/news/lq/news_01.jpg',
		labels: [{ label: 'tips', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-24T15:07:45.868917+00:00',
		description:
			'<strong>Met</strong> ‘Nieuws in de klas’ brengt Mediawijs een rijk aanbod aan kranten en digitale media in jouw klaslokaal. Vandaag lanceren de - bestaande en nieuwe - partners in het project een vernieuwde website met een pak meer materiaal, o.a. van Het Archief voor Onderwijs. Mediawijs, de Vlaamse Nieuwsmedia, WE MEDIA, Media.21, VRT en VIAA slaan de handen in elkaar en staan voortaan samen in voor jouw afspraak met de actualiteit.',
		title: 'Testland',
		id: 53,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/news/lq/news_02.jpg',
		labels: [
			{ label: 'projecten', id: 2 },
			{ label: 'in de kijker', id: 3 },
			{ label: 'tips', id: 1 },
		],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-20T16:45:40.346734+00:00',
		description: null,
		title: 'Ontdek',
		id: 31,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/news/lq/news_04.jpg',
		labels: [{ label: 'tips', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-20T17:14:26.616585+00:00',
		description:
			'Katrijn bouwt als gedetacheerde leerkracht mee aan de collecties voor de kunstvakken op Het Archief voor Onderwijs. Ze ploos het beeldmateriaal van onze partners grondig uit en koos op basis van de leerplannen voor de modevakken fascinerende fragmenten uit o.a. modeprogramma’s en catwalks die je leerlingen zeker zullen prikkelen.',
		title: 'Hulp',
		id: 32,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/news/lq/news_05.jpg',
		labels: [{ label: 'tips', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-22T10:54:22.744477+00:00',
		description:
			'Meer video en audio in je les? Ontdek op de online beeldbank Het Archief voor Onderwijs\neen gevarieerd aanbod aan Nederlandstalige audiovisuele fragmenten.',
		title: 'Over ons｜Het Archief voor Onderwijs',
		id: 36,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/news/lq/news_06.jpg',
		labels: [{ label: 'tips', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-30T15:15:57.779099+00:00',
		description: null,
		title: 'test',
		id: 73,
		thumbnail_path: 'http://master.viaa2.mono.digital/images/photos/klas.jpg',
		labels: [{ label: 'tips', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-09T10:52:03.051781+00:00',
		description: null,
		title: 'FAQ pagina met blocks',
		id: 15,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-30T15:35:41.586532+00:00',
		description: null,
		title: 'qewqweqw',
		id: 76,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 1 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-31T15:49:05.678252+00:00',
		description: null,
		title: 'qweweq',
		id: 78,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 2 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-02-03T14:47:22.718945+00:00',
		description: null,
		title: 'wqewq',
		id: 85,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 2 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-01-30T15:54:58.997813+00:00',
		description: null,
		title: 'Test-pagina van Benjamón',
		id: 77,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 2 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-02-11T13:37:49.376298+00:00',
		description: null,
		title: 'wqe',
		id: 105,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 2 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-02-09T20:53:07.289224+00:00',
		description: null,
		title: 'weqw',
		id: 97,
		thumbnail_path: image500x200,
		labels: [{ label: 'projecten', id: 2 }],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-02-11T14:12:16.357995+00:00',
		description: null,
		title: 'both test 1 and test 2',
		id: 106,
		thumbnail_path: image500x200,
		labels: [
			{ label: 'tips', id: 1 },
			{ label: 'projecten', id: 2 },
		],
		path: '/fake-page',
	},
	{
		content_width: 'REGULAR',
		created_at: '2020-02-04T11:42:59.966439+00:00',
		description: 'test',
		title: 'no labels test',
		id: 86,
		thumbnail_path: image500x200,
		labels: [],
		path: '/fake-page',
	},
];
